# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pylint pytest
      - run:
          name: Run pylint
          command: |
            . venv/bin/activate
            pylint devchat
      - run:
          name: Run pytest
          command: |
            . venv/bin

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
