version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Run Pylint
          command: |
            poetry run pylint devchat tests
      - run:
          name: Run Pytest
          command: |
            poetry run pytest
workflows:
  version: 2
  build:
    jobs:
      - build
